### ISSUE TITLE
Please Release Version: 3.10.0

### ISSUE THREAD

**Issue by acotiuga** [webjars/fullcalendar#21]
I would like to use the latest version from the 3.x cycle for a project that is using Bootstrap 3. Thank you!

**Comment by jamesward** [comment]
`3.10.2` will be released shortly.

**Comment by acotiuga** [comment]
Could you confirm that the new webjar will be in the group `org.webjars`? I only see the new one in groups like `"org.webjars.bower` and `org.webjars.npm`.

**Comment by jamesward** [comment]
Yeah, it will be in `org.webjars` and should be in Maven Central in a few hours.
